name: binaural_beats
description: 'An application to generate binaural beats.'
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flex_color_picker: ^3.5.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  intl: any
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  fake_async: ^1.3.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  shared_preferences_platform_interface: ^2.4.1

flutter:
  assets:
    - assets/app_icon.png
  generate: true
  uses-material-design: true
